all: 

help: all

dist:
	@[ -f configure ] || autoreconf -i
	@[ -f Makefile  ] || PKG_CONFIG=true ./configure
	@make dist

srcpkg: dist

develop:
	@[ -f configure ] || autoreconf -i
	@[ -f Makefile  ] || CFLAGS="-Wall -ggdb3" ./configure

release: dist
	@make package
