all: 

help: all

dist:
	@[ -f configure ] || autoreconf -i
	@[ -f Makefile  ] || PKG_CONFIG=true ./configure
	@make dist

srcpkg: dist

develop:
	@[ -f configure ] || autoreconf -i
	@[ -f Makefile  ] || CFLAGS="-Wall -ggdb3" ./configure

release: dist
	@make package

venv:
	python3 -m venv venv

upload_release: venv
	python3 scripts/upload_release.py globus-gridftp-server-hpss*.rpm

.SILENT:
