
_GLOBUS_CFLAGS=`echo $(GLOBUS_CFLAGS) | sed 's,-I,-idirafter,g'`

MODULE_CPP_FLAGS=         \
	$(TIRPC_CFLAGS)   \
	$(OPENSSL_CFLAGS) \
	$(_GLOBUS_CFLAGS) \
	$(HPSS_CPPFLAGS)

MODULE_LD_FLAGS=@HPSS_LDFLAGS@

#
# IU and NERSC report that using krb fails because libhpssgss.so doesn't link
# against libhpsskrbauth.so. NERSC reported that libhpssunixauth.so was
# necessary in their environment. It is necessary to link these here; the
# XDR/libtirpc issue causes the runtime dynamic linking to fail without this.
#
MODULE_LIBS=            \
	$(TIRPC_LIBS)   \
	$(OPENSSL_LIBS) \
	$(GLOBUS_LIBS)  \
	$(HPSS_LIBS)

